// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
	"encoding/json"
)

type Declaration struct {
	Identifier  string
	Type        string
	Payload     json.RawMessage
	CreatedAt   string
	UpdatedAt   string
	TouchedCt   int32
	ServerToken string
}

type EnrollmentSet struct {
	EnrollmentID string
	SetName      string
	CreatedAt    string
	UpdatedAt    string
}

type SetDeclaration struct {
	SetName               string
	DeclarationIdentifier string
	CreatedAt             string
	UpdatedAt             string
}

type StatusDeclaration struct {
	EnrollmentID          string
	DeclarationIdentifier string
	Active                bool
	Valid                 string
	ServerToken           string
	ItemType              string
	Reasons               []byte
	StatusID              sql.NullString
	CreatedAt             string
	UpdatedAt             string
}

type StatusError struct {
	ID           uint64
	EnrollmentID string
	Path         string
	Error        []byte
	StatusID     sql.NullString
	CreatedAt    string
	UpdatedAt    string
}

type StatusReport struct {
	ID           uint64
	EnrollmentID string
	StatusReport []byte
	StatusID     sql.NullString
	CreatedAt    string
	UpdatedAt    string
}

type StatusValue struct {
	EnrollmentID  string
	Path          string
	ContainerType string
	ValueType     string
	Value         string
	StatusID      sql.NullString
	CreatedAt     string
	UpdatedAt     string
}
