// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Declaration struct {
	Identifier  string
	Type        string
	Payload     json.RawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
	TouchedCt   int32
	ServerToken string
}

type DeclarationReference struct {
	DeclarationIdentifier string
	DeclarationReference  string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type EnrollmentSet struct {
	EnrollmentID string
	SetName      string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type SetDeclaration struct {
	SetName               string
	DeclarationIdentifier string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type StatusDeclaration struct {
	EnrollmentID          string
	DeclarationIdentifier string
	Active                bool
	Valid                 string
	ServerToken           string
	ItemType              string
	Reasons               json.RawMessage
	StatusID              sql.NullString
	CreatedAt             time.Time
	UpdatedAt             string
}

type StatusError struct {
	EnrollmentID string
	Path         string
	Error        json.RawMessage
	StatusID     sql.NullString
	RowCount     int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type StatusReport struct {
	EnrollmentID string
	StatusReport json.RawMessage
	StatusID     sql.NullString
	RowCount     int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type StatusValue struct {
	EnrollmentID  string
	Path          string
	ContainerType string
	ValueType     string
	Value         string
	StatusID      sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
