// Code generated by "admgenddmrefs"; DO NOT EDIT.
package ddm

// IdentifierRefs is a map of declaration type to payload key paths.
// These key paths contain the identifiers of dependent declarations.
var IdentifierRefs = map[string][][]string{
	"com.apple.activation.simple": {
		{"StandardConfigurations"},
	},
	"com.apple.configuration.account.caldav": {
		{"AuthenticationCredentialsAssetReference"},
	},
	"com.apple.configuration.account.carddav": {
		{"AuthenticationCredentialsAssetReference"},
	},
	"com.apple.configuration.account.exchange": {
		{"UserIdentityAssetReference"},
		{"AuthenticationCredentialsAssetReference"},
		{"AuthenticationIdentityAssetReference"},
		{"SMIME", "Signing", "IdentityAssetReference"},
		{"SMIME", "Encryption", "IdentityAssetReference"},
	},
	"com.apple.configuration.account.google": {
		{"UserIdentityAssetReference"},
	},
	"com.apple.configuration.account.ldap": {
		{"AuthenticationCredentialsAssetReference"},
	},
	"com.apple.configuration.account.mail": {
		{"UserIdentityAssetReference"},
		{"IncomingServer", "AuthenticationCredentialsAssetReference"},
		{"OutgoingServer", "AuthenticationCredentialsAssetReference"},
		{"SMIME", "Signing", "IdentityAssetReference"},
		{"SMIME", "Encryption", "IdentityAssetReference"},
	},
	"com.apple.configuration.account.subscribed-calendar": {
		{"AuthenticationCredentialsAssetReference"},
	},
	"com.apple.configuration.management.test": {
		{"EchoDataAssetReference"},
	},
	"com.apple.configuration.screensharing.connection": {
		{"AuthenticationCredentialsAssetReference"},
	},
	"com.apple.configuration.security.certificate": {
		{"CredentialAssetReference"},
	},
	"com.apple.configuration.security.identity": {
		{"CredentialAssetReference"},
	},
	"com.apple.configuration.security.passkey.attestation": {
		{"AttestationIdentityAssetReference"},
	},
	"com.apple.configuration.services.configuration-files": {
		{"DataAssetReference"},
	},
}
