// Code generated by "admgencmd"; DO NOT EDIT.
// Source: declarativemanagement.yaml
// Options: no-shared=true,no-depend=true,no-responses=true
package notifier

const DeclarativeManagementRequestType = "DeclarativeManagement"

// DeclarativeManagementPayload is the "inner" command-specific payload for the "DeclarativeManagement" Apple MDM command.
type DeclarativeManagementPayload struct {
	Data                         *[]byte `plist:",omitempty"`
	RequestType                  string  // must be set to "DeclarativeManagement"
	RequestRequiresNetworkTether *bool   `plist:",omitempty"`
}

// DeclarativeManagementCommand is the top-level structure for the "DeclarativeManagement" Apple MDM command.
type DeclarativeManagementCommand struct {
	Command     DeclarativeManagementPayload
	CommandUUID string
}

// NewDeclarativeManagementCommand creates a new "DeclarativeManagement" Apple MDM command.
func NewDeclarativeManagementCommand() *DeclarativeManagementCommand {
	return &DeclarativeManagementCommand{Command: DeclarativeManagementPayload{RequestType: DeclarativeManagementRequestType}}
}
